
export  const GET_REQUSET_SUCESS = "GET_REQUSET_SUCESS"
export  const GET_REQUSET_FAILURE = "GET_REQUSET_FAILURE"
export  const GET_REQUSET_LOADING= "GET_REQUSET_LOADING"


export  const DELETE_REQUEST_LOADING = "DELETE_REQUEST_LOADING"
export  const DELETE_REQUEST_SUCESS= "DELETE_REQUEST_SUCESS"
export  const DELETE_REQUEST_FAILURE= "DELETE_REQUEST_FAILURE"